### ISSUE TITLE
[BUG] ZlibError: zlib: incorrect data check

### ISSUE THREAD

**Issue by dela1s** [create-discord-bot/create-discord-bot#18] opened 2023-03-13 19:27 UTC
**Description**
ZlibError: zlib: incorrect data check

**System Information**
NodeJS version: 18.15.0
NPM version: 9.6.1
Package version: 1.3.41
OC: Windows 11

**Comment by FLzyy** [comment] 2023-03-14 01:28
Could you show the complete error message that includes the error stack?

**Comment by FLzyy** [comment] 2023-03-14 01:53
This seems to be an upstream issue from giget, I'll try to replace it with another dependency or just create a simple custom solution. 

Thank you for reporting.

**Comment by Dela1s** [comment] 2023-03-14 10:38
Then it turns out this is an error from giget?

**Comment by FLzyy** [comment] 2023-03-14 10:44
Yep, it's an issue with one of giget's dependencies node-tar.

**Comment by dela1s** [comment] 2023-03-14 10:49
Then maybe write to them about it?

**Comment by FLzyy** [comment] 2023-03-14 10:59
I will, in the meantime this project will use a temporary solution for now until the issue is fixed on giget's end.

**Comment by dela1s** [comment] 2023-03-14 11:09
Ok.

**Comment by Dela1s** [comment] 2023-03-14 17:21
Why don't you want to completely give up giget?

**Comment by dela1s** [comment] 2023-03-14 20:06
NodeJS version: 16.19.1 | NPM version: 9.6.1 everything works fine. And above the NodeJS version there are already errors.

**Comment by dela1s** [comment] 2023-03-16 08:22
Okay, I saw you doing branch issue18, so this issue can be closed?

**Closed as completed** 2023-03-16 20:26 UTC
